version: 2

jobs:
  build:
    docker:
      - image: nixorg/nix:circleci
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-{{ checksum "shell.nix" }}-{{ checksum "Pipfile.lock" }}-2

      - run: ci/setup-nix
      - run: direnv exec . make check
      - run: direnv exec . ci/run

      - save_cache:
          paths:
            - /nix
            - /root/.cache
            - /root/.local/share/virtualenvs
          key: v1-{{ checksum "shell.nix" }}-{{ checksum "Pipfile.lock" }}-2
